---
title: "GADGET Report"
output:
  html_document
params:
  pheno: NA
  dir: NA

---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
```

```{r, GRS_ANOVA, echo = FALSE, include = F}
library(ggplot2)
library(RColorBrewer)
library(data.table)
library(stringr)
library(DT)
library(gridExtra)
library(ggvis)
if("leaflet" %in% (.packages())){
  detach("package:leaflet", unload=TRUE) 
}
# detach("package:leaflet", unload=TRUE)
library(leaflet)
# library(leaflet, lib.loc = "/projects/grs-data/R/x86_64-redhat-linux-gnu-library/3.4/")
library(shinydashboard, lib.loc = "/projects/grs-data/R/x86_64-redhat-linux-gnu-library/3.4/")
library(stargazer, lib.loc = "/projects/grs-data/R/x86_64-redhat-linux-gnu-library/3.4/")

#source("/projects/grs-data/compute-app/sources.R", envir=globalenv())
# metadata files
readGrs = function(fileName, sampleInfo) {
  grs = my.read.table(fileName, comment.char = "##")
  colnames(grs) = c("IND", "GRS")
  grs = merge(grs, sampleInfo, by = "IND")
}

my.read.table = function(fileName, comment.char) {
  clean.lines = sub(paste0(comment.char, ".*"), "", readLines(fileName))
  clean.lines = sub("SAMPLE.*", "", clean.lines)
  read.table(text = paste(clean.lines, collapse = "\n"))
}
# metadata files
sampleInfo = read.csv("/projects/grs-data/compute-app/data/20130606_sample_info.csv", fileEncoding = "latin1")
sampleInfo = sampleInfo[, c(1, 3, 5)]
colnames(sampleInfo) = c("IND", "POP", "GEN")
supInfo = read.csv("/projects/grs-data/compute-app/data/super_population_info.csv", fileEncoding = "latin1")
supInfo = supInfo[, c(1, 3, 7)]
colnames(supInfo) = c("POP", "SUP", "FULL")
sampleInfo = merge(sampleInfo, supInfo, by = "POP")
supNames = c("AFR", "EUR", "AMR", "SAS", "EAS")
c5 = c("#484496", "#F4A500", "#328A4F", "#944116", "#D92414")
names(c5) = supNames



outdir = params$dir
    file = paste(outdir, params$pheno, ".txt", sep = "")
    grs = readGrs(file, sampleInfo)
    grsMod = lm(GRS ~ SUP, data = grs)
    grsAno = anova(grsMod)
    fstat = grsAno$`F value`[1]
    pval = grsAno$`Pr(>F)`[1]
    
    # Medians
    grsdt = as.data.table(grs)
    grsdt$GRS = as.numeric(grsdt$GRS)
    grsdt[, SUPMED := median(GRS), by = SUP]
    medians = as.data.frame(grsdt[which(!duplicated(grsdt$SUP)), 5:7, with = F])
    orderedSup = medians$FULL[order(medians$SUPMED)]
    grs$FULL = ordered(grs$FULL, levels = orderedSup)
    grsdt = as.data.table(grs)
    grsdt$GRS = as.numeric(grsdt$GRS)
    grsdt[, SUPMED := median(GRS), by = SUP]
    grsdt[, POPMED := median(GRS), by = POP]
    mediansSUP = as.data.frame(grsdt[which(!duplicated(grsdt$SUP)), 5:7, with = F])
    mediansPOP = as.data.frame(grsdt[which(!duplicated(grsdt$POP)), c(3,5,8), with = F])
    # ANOVA
    # grsMod = lm(GRS ~ SUP, data = grs)
    # grsAno = anova(grsMod)
    # fstat = grsAno$`F value`[1]
    # pval = grsAno$`Pr(>F)`[1]
    
    # # Medians
    # grsdt = as.data.table(grs)
    # grsdt$GRS = as.numeric(grsdt$GRS)
    # grsdt[, SUPMED := median(GRS), by = SUP]
    # medians = as.data.frame(grsdt[which(!duplicated(grsdt$SUP)), 5:6, with = F])
    # orderedSup = medians$SUP[order(medians$SUPMED)]
    # grs$SUP = ordered(grs$SUP, levels = orderedSup)
```
### Global Distribution

```{r,map,fig.width=9, fig.height=4, echo=FALSE, include=T}    
# library(leaflet, lib.loc = "/projects/grs-data/R/x86_64-redhat-linux-gnu-library/3.4/")

points = read.csv("/projects/grs-data/compute-app/data/geo.csv")
# mediansPOP = medians()[[2]]
    points = merge(points, mediansPOP, by = "POP")
    points$POPMEDScaled = points$POPMED / mean(points$POPMED)
    points$description = paste0(
      "<p style=\"color:black\"><b>Sample information: </b>",
      points$description,
      " (",
      points$POP,
      ")",
      ". <b>Population size:</b> ",
      points$nSample,
      ". <b>Median PTS for this population:</b> ",
      round(points$POPMED,4),
      "</p>"
    )
    # Colors
    supNames = c("AFR", "EUR", "AMR", "SAS", "EAS")
c5 = c("#484496", "#F4A500", "#328A4F", "#944116", "#D92414")
names(c5) = supNames
fullNames = c("African", "European", "Admixed American", "Southeast Asian", "East Asian")
cF = c("#484496", "#F4A500", "#328A4F", "#944116", "#D92414")
    names(cF) = fullNames
    pal <- colorFactor(c5, levels = names(c5))
    palF <- colorFactor(cF, levels = names(cF))
    leaflet() %>%
      # addTiles(options = providerTileOptions(noWrap = TRUE))  %>% 
      # addProviderTiles(providers$Thunderforest)%>%
      addProviderTiles("CartoDB", options = providerTileOptions(noWrap = TRUE)) %>%
      fitBounds(
        lng1 = max(points$lng),
        lat1 = 50, 
        lng2 = min(points$lng),
        lat2 = min(points$lat)
      ) %>%
      addCircleMarkers(
        lng = ~ lng,
        lat = ~ lat,
        weight = 1,
        radius = ~ (20*2^POPMEDScaled/max(POPMEDScaled)),
        popup = ~ description,
        color = ~ pal(SUP.x),
        stroke = F,
        fillOpacity = 0.5,
        data = points
      ) %>%
      addLegend(
        "bottomright",
        pal = palF,
        values = fullNames,
        title = "Populations"
      )

# medians <- function(){
#         # Medians
#         grsdt = as.data.table(grs)
#         grsdt$GRS = as.numeric(grsdt$GRS)
#         grsdt[, SUPMED:=median(GRS), by = SUP]
#         grsdt[, POPMED:=median(GRS), by = POP]
#         mediansSUP = as.data.frame(grsdt[which(!duplicated(grsdt$SUP)), 5:6, with = F])
#         mediansPOP = as.data.frame(grsdt[which(!duplicated(grsdt$POP)), c(3,7), with=F])
#         list(mediansSUP=mediansSUP, mediansPOP=mediansPOP)
#       }
#         points = read.csv("/projects/grs-data/compute-app/data/geo.csv")
#         mediansPOP = medians()[[2]]
#         points = merge(points, mediansPOP, by="POP")
#         points$POPMEDScaled = points$POPMED/mean(points$POPMED)
#         points$description = paste0("<p style=\"color:black\"><b>Sample information: </b>", points$description," (",points$POP, ")", ". <b>Population size:</b> ", points$nSample, ". <b>Median PTS for this population:</b> ", points$POPMED, "</p>")
#         # Colors
#        supNames = c("AFR", "EUR", "AMR", "SAS", "EAS")
# c5 = c("#484496", "#F4A500", "#328A4F", "#944116", "#D92414")
# names(c5) = supNames
# fullNames = c("African", "European", "Admixed American", "Southeast Asian", "East Asian")
# cF = c("#484496", "#F4A500", "#328A4F", "#944116", "#D92414")
#     names(cF) = fullNames
#     pal <- colorFactor(c5, levels = names(c5))
#     palF <- colorFactor(cF, levels = names(cF))

#        M<- leaflet() %>%
#           addTiles(options = providerTileOptions(noWrap = TRUE)) %>% 
#   fitBounds(lng1 = max(points$lng),lat1 = 50,
#             lng2 = min(points$lng),lat2 = min(points$lat)) %>%
#           addCircleMarkers(lng = ~lng, lat = ~lat, weight = 1,
#                      radius = ~(16^POPMEDScaled), popup = ~description,
#                      color = ~pal(SUP),
#                      stroke = F,
#                      fillOpacity = 0.5,
#                      data=points
#                      ) %>% addLegend("bottomright",pal = palF, values = fullNames, title="Populations")
#      M

```



### PTS distribution by population 

```{r,stripplot,fig.width=10, fig.height=6, echo=FALSE}
# medians <- function(){
#     grs = grsdt
#     # Medians
#     grsdt = as.data.table(grs)
#     grsdt$GRS = as.numeric(grsdt$GRS)
#     grsdt[, SUPMED := median(GRS), by = SUP]
#     grsdt[, POPMED := median(GRS), by = POP]
#     mediansSUP = as.data.frame(grsdt[which(!duplicated(grsdt$SUP)), 5:7, with = F])
#     mediansPOP = as.data.frame(grsdt[which(!duplicated(grsdt$POP)), c(3,5,8), with =
#                                        F])
#     list(mediansSUP = mediansSUP, mediansPOP = mediansPOP)
#   }
    grsdf = as.data.table(grs)
    title = params$pheno
    medians = mediansPOP
    orderedPop = medians$POP[order(medians$POPMED)]
    medians = medians[order(medians$POPMED),]
    
    grsdf$POP = ordered(grsdf$POP, levels = orderedPop)
    grsdf = grsdf[order(grsdf$POP, grsdf$GRS),]
    grslist = split(grsdf, f = grsdf$POP)
    names(grslist) = orderedPop
    
    grslist = lapply(grslist, function(x) {
      x$x = rep(1, nrow(x))
      x$x = 100 * x$x / sum(x$x)
      x
    })
    
    
    grsdf = do.call(rbind, grslist)
    spacer_size = 10
    grsdf$x = cumsum(grsdf$x)
    ymax = max(grsdf$GRS) * 1.2
    ymin = min(grsdf$GRS) * 0.8
    medians$x = seq(1, nrow(medians) * 100, by = 100)
    medians$xend = seq(100, nrow(medians) * 100, by = 100)
    medians$midx = medians$x + (medians$xend - medians$x + 1) / 2
    if (nrow(medians) %% 2 == 0) {
      medians$col = factor(rep(1:2, nrow(medians) / 2))
    } else{
      medians$col = factor(c(rep(1:2, (
        nrow(medians) - 1
      ) / 2), 1))
    }
    medians$midy = (ymax - ymin) / 2 + ymin
    medians$h = ymax - ymin
    medians$ymin = ymin
    
    ggplot() +
      geom_tile(data = medians, aes(
        x = midx,
        y = midy,
        fill = col,
        height = h
      )) +
      scale_fill_manual(values = c("lightgrey", "white"),
                        guide = F) +
      geom_point(
        data = grsdf,
        aes(x = x, y = GRS, col = SUP),
        alpha = 0.5,
        size = 1.5
      ) +
      scale_color_manual(values = c5, guide = F) +
      geom_segment(
        data = medians,
        aes(
          x = x,
          y = POPMED,
          xend = xend,
          yend = POPMED
        ),
        size = 1,
        col = "red"
      ) +
      theme_bw() +
      theme(
        panel.grid = element_blank(),
        panel.border = element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
        axis.title.x = element_blank()
      ) + theme(text = element_text(size=15)) +
      labs(y = "Polygenic Trait Score", x = "Population", title = title) +
      geom_text(
        data = medians,
        aes(x = midx, y = ymin, label = POP, col=SUP),
        fontface="bold",
        angle = -45,
        vjust = 1,
        hjust = -0.2,
        size = 4
      ) +
      coord_cartesian(ylim = c(ymin - (ymax - ymin) * 0.1, ymax))


```

### PTS distribution by continental group


```{r,GRS_PLOT, fig.width=10, fig.height=6, echo=FALSE} 

    # Boxplot
    #title = ifelse(is.null(title), "", title)
    ggplot(grs, aes(x = FULL, y = GRS)) +
      geom_point(
        position = position_jitter(width = 0.6, height = 0.00),
        aes(
          col = FULL,
          size = 0.001,
          fill = SUP
        ),
        colour = "black",
        pch = 21,
        show.legend = F
      ) +
      scale_fill_manual(values = c5, guide = F) +
      geom_boxplot(outlier.shape = NA, alpha = 0.3) +
      theme_bw() +
      theme(panel.grid = element_blank()) + theme(text = element_text(size=15)) +
      labs(
        title = gsub(".txt", "", params$pheno),
        x = paste(
          "F value=",
          format(fstat, digit = 5),
          ", P-value =",
          format(pval, digit = 3)
        ),
        y = "Polygenic Trait Score"
      )

```